# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20180112_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
