# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-created_at', '-pk')},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
